// SPDX-License-Identifier: MIT
//
// @ruflo/host-pi-dev — pi.dev (badlogic / earendil-works Pi coding agent)
// host adapter.
//
// CRITICAL CLARIFICATION: pi.dev is NOT Inflection's Pi.ai consumer chatbot.
// It is the badlogic Pi coding agent harness. References:
//   - Landing: https://pi.dev/
//   - Source: https://github.com/badlogic/pi-mono (packages/coding-agent)
//
// Verified integration surface (from research):
//   - Config: ~/.pi/agent/ (global) and .pi/ (project)
//   - Instructions: AGENTS.md and SYSTEM.md
//   - Trust: ~/.pi/agent/trust.json
//   - Extensions are TypeScript modules, installed via
//     `pi install npm:@foo/pi-tools` or `pi install git:github.com/...`
//   - Extensions register tools via pi.registerTool({...}) and commands
//     via pi.registerCommand(...)
//
// CRITICAL DESIGN NOTE: Pi explicitly ships with NO MCP. From the README's
// "What we didn't build": "No MCP. Build CLI tools with READMEs (see Skills),
// or build an extension that adds MCP support."
//
// Implication for this adapter: instead of generating MCP config, we
// generate a Pi extension entry point that calls pi.registerTool({...})
// for each kernel-exposed tool. The wasm kernel is still loaded for
// memory/routing/intelligence — only the MCP plumbing is bypassed.

import type { HostAdapter, HarnessSpec, ToolSpec } from '@ruflo/kernel';

export const HOST_NAME = 'pi-dev' as const;

/**
 * Generate the TypeScript source for a Pi extension that registers each
 * kernel-exposed tool via pi.registerTool({...}). The extension is bundled
 * into the generated harness's npm package and consumers run
 * `pi install npm:<harness-name>` to get it.
 */
export function extensionSource(spec: HarnessSpec): string {
  const tools = spec.tools ?? [];
  const registrations = tools.map(t => `  pi.registerTool(${JSON.stringify({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  }, null, 4).replace(/\n/g, '\n  ')}, async (args) => {
    // Kernel dispatches the actual tool execution.
    const { loadKernel } = await import('@ruflo/kernel');
    const kernel = await loadKernel();
    return kernel.invokeTool(${JSON.stringify(t.name)}, args);
  });`).join('\n\n');

  return `// SPDX-License-Identifier: MIT
// Auto-generated by @ruflo/host-pi-dev.
// Edit @ruflo/kernel's tool registry; do not edit this file directly.

import type { PiContext } from 'pi-agent-sdk';

export async function register(pi: PiContext): Promise<void> {
${registrations || '  // No tools declared in harness spec.'}
}
`;
}

/**
 * Generate AGENTS.md content with the harness's system prompt and agent
 * roster — Pi reads instructions from this file at session start.
 */
export function agentsMarkdown(spec: HarnessSpec): string {
  return `# ${spec.name}

${spec.description ?? ''}

## Agents

${(spec.agents ?? []).map(a => `### ${a.name}\n\n${a.systemPrompt ?? ''}`).join('\n\n')}
`;
}

export const adapter: HostAdapter = {
  name: HOST_NAME,
  generateConfig: (spec: HarnessSpec) => ({
    'pi-extension/src/index.ts': extensionSource(spec),
    'AGENTS.md': agentsMarkdown(spec),
    'SYSTEM.md': spec.systemPrompt ?? '',
  }),
};

export default adapter;
