// SPDX-License-Identifier: MIT
//
// @metaharness/host-pi-dev — pi.dev (badlogic / earendil-works Pi coding agent)
// host adapter.
//
// CRITICAL CLARIFICATION: pi.dev is NOT Inflection's Pi.ai consumer chatbot.
// It is the badlogic Pi coding agent harness. References:
//   - Landing: https://pi.dev/
//   - Source: https://github.com/badlogic/pi-mono (packages/coding-agent)
//
// Verified integration surface (from research):
//   - Config: ~/.pi/agent/ (global) and .pi/ (project)
//   - Instructions: AGENTS.md and SYSTEM.md
//   - Trust: ~/.pi/agent/trust.json
//   - Extensions are TypeScript modules, installed via
//     `pi install npm:@foo/pi-tools` or `pi install git:github.com/...`
//   - Extensions register tools via pi.registerTool({...}) and commands
//     via pi.registerCommand(...)
//
// CRITICAL DESIGN NOTE: Pi explicitly ships with NO MCP. From the README's
// "What we didn't build": "No MCP. Build CLI tools with READMEs (see Skills),
// or build an extension that adds MCP support."
//
// Implication for this adapter: instead of generating MCP config, we
// generate a Pi extension entry point that calls pi.registerTool({...})
// for each kernel-exposed tool. The wasm kernel is still loaded for
// memory/routing/intelligence — only the MCP plumbing is bypassed.

import type { HostAdapter, HarnessSpec, ToolSpec } from '@metaharness/kernel';

export const HOST_NAME = 'pi-dev' as const;

/**
 * Generate the TypeScript source for a Pi extension that registers each
 * kernel-exposed tool via pi.registerTool({...}). The extension is bundled
 * into the generated harness's npm package and consumers run
 * `pi install npm:<harness-name>` to get it.
 */
export function extensionSource(spec: HarnessSpec): string {
  const tools = spec.tools ?? [];
  const registrations = tools.map(t => `  pi.registerTool(${JSON.stringify({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  }, null, 4).replace(/\n/g, '\n  ')}, async (args) => {
    // Kernel dispatches the actual tool execution.
    const { loadKernel } = await import('@metaharness/kernel');
    const kernel = await loadKernel();
    return kernel.invokeTool(${JSON.stringify(t.name)}, args);
  });`).join('\n\n');

  return `// SPDX-License-Identifier: MIT
// Auto-generated by @metaharness/host-pi-dev.
// Edit @metaharness/kernel's tool registry; do not edit this file directly.

import type { PiContext } from 'pi-agent-sdk';

export async function register(pi: PiContext): Promise<void> {
${registrations || '  // No tools declared in harness spec.'}
}
`;
}

/**
 * Generate AGENTS.md content with the harness's system prompt and agent
 * roster — Pi reads instructions from this file at session start.
 */
export function agentsMarkdown(spec: HarnessSpec): string {
  return `# ${spec.name}

${spec.description ?? ''}

## Agents

${(spec.agents ?? []).map(a => `### ${a.name}\n\n${a.systemPrompt ?? ''}`).join('\n\n')}
`;
}

/**
 * ADR-044: emit `trust.json` for `~/.pi/agent/trust.json`. Pi gates extension
 * tool execution behind a trust file; a generated harness ships a trust entry
 * for its own extension so `pi install npm:<harness>` is trusted out of the
 * box (rather than every tool prompting). Permission allow/deny patterns from
 * the harness posture (ADR-022) ride along so Pi can scope tool access.
 */
export function trustJson(spec: HarnessSpec): string {
  return JSON.stringify({
    schema: 1,
    trusted_extensions: [
      {
        // The harness publishes its Pi extension under the harness package name.
        name: spec.name,
        source: `npm:${spec.name}`,
        // Default-deny posture (ADR-022) carried through for tool scoping.
        allow: spec.permissions?.allow ?? [],
        deny: spec.permissions?.deny ?? [],
      },
    ],
  }, null, 2) + '\n';
}

export const adapter: HostAdapter = {
  name: HOST_NAME,
  generateConfig: (spec: HarnessSpec) => ({
    'pi-extension/src/index.ts': extensionSource(spec),
    'AGENTS.md': agentsMarkdown(spec),
    'SYSTEM.md': spec.systemPrompt ?? '',
    // ADR-044: was missing — Pi's trust gate file.
    'trust.json': trustJson(spec),
  }),
};

export default adapter;
