// SPDX-License-Identifier: MIT
//
// The MCP primitive — modular, gated, security-first (ADR-022).
//
// MCP is ONE selectable primitive, not the product. When enabled it emits a
// small, self-contained MCP surface into the harness: a JSON-RPC server
// (stdio for `local`, Streamable HTTP for `remote`), deterministic tool /
// resource / prompt registries, an enforced security policy, an append-only
// audit log, and (remote only) an auth layer. Every capability is default-deny:
// the author opts INTO network / shell / file-write, never out of safety.
//
// The policy is emitted twice — as enforced TS (policy.ts) and as inert data
// (.harness/mcp-policy.json) — so it can be scanned (`harness mcp-scan`),
// audited, and folded into the witness manifest.

import type { GenFile, HarnessConfig, McpPolicy } from './types';

const HEADER = '// SPDX-License-Identifier: MIT\n// Generated by agent-harness-generator — MCP primitive (ADR-022).\n';

export function mcpFiles(cfg: HarnessConfig): GenFile[] {
  if (cfg.primitives.mcp === 'off') return [];
  const remote = cfg.primitives.mcp === 'remote';
  const files: GenFile[] = [
    { path: 'src/mcp/server.ts', content: serverTs(cfg, remote) },
    { path: 'src/mcp/tools.ts', content: toolsTs(cfg) },
    { path: 'src/mcp/resources.ts', content: resourcesTs(cfg) },
    { path: 'src/mcp/prompts.ts', content: promptsTs(cfg) },
    { path: 'src/mcp/policy.ts', content: policyTs() },
    { path: 'src/mcp/audit.ts', content: auditTs() },
    { path: '.harness/mcp-policy.json', content: policyJson(cfg.mcpPolicy) },
    { path: '.harness/mcp-capabilities.json', content: capabilitiesJson(cfg) },
  ];
  if (remote) files.push({ path: 'src/mcp/auth.ts', content: authTs() });
  return files;
}

// --- enforced policy (TS) --------------------------------------------------

function policyTs(): string {
  return `${HEADER}
import policyData from '../../.harness/mcp-policy.json' with { type: 'json' };

export interface ToolCtx {
  /** Declared capabilities this tool needs. */
  needs: { network?: boolean; shell?: boolean; fileWrite?: boolean };
  /** Author/host has flagged this tool dangerous. */
  dangerous?: boolean;
}

export interface PolicyDecision {
  allowed: boolean;
  reason: string;
  requiresApproval: boolean;
}

export const POLICY = policyData as {
  defaultDeny: boolean;
  allowNetwork: boolean;
  allowShell: boolean;
  allowFileWrite: boolean;
  requireApprovalForDangerous: boolean;
  toolTimeoutMs: number;
  maxToolCallsPerTurn: number;
  auditLog: boolean;
};

/**
 * The single gate every tool call passes through. Default-deny: a capability
 * the policy does not grant is refused, not silently allowed.
 */
export function decide(ctx: ToolCtx): PolicyDecision {
  if (ctx.needs.network && !POLICY.allowNetwork) {
    return { allowed: false, reason: 'network not permitted by policy', requiresApproval: false };
  }
  if (ctx.needs.shell && !POLICY.allowShell) {
    return { allowed: false, reason: 'shell not permitted by policy', requiresApproval: false };
  }
  if (ctx.needs.fileWrite && !POLICY.allowFileWrite) {
    return { allowed: false, reason: 'file-write not permitted by policy', requiresApproval: false };
  }
  const requiresApproval = !!ctx.dangerous && POLICY.requireApprovalForDangerous;
  return { allowed: true, reason: 'permitted', requiresApproval };
}

/** Wrap an async tool body with the policy's per-call timeout. */
export async function withTimeout<T>(fn: () => Promise<T>): Promise<T> {
  let timer: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error('tool timed out')), POLICY.toolTimeoutMs);
  });
  try {
    return await Promise.race([fn(), timeout]);
  } finally {
    clearTimeout(timer!);
  }
}
`;
}

// --- audit log -------------------------------------------------------------

function auditTs(): string {
  return `${HEADER}
import { appendFile } from 'node:fs/promises';
import { POLICY } from './policy.js';

/** One audit record per tool call. Append-only; never mutated. */
export interface AuditEntry {
  ts: string;
  tool: string;
  decision: 'allowed' | 'denied' | 'approval-required' | 'error';
  reason: string;
  durationMs?: number;
}

const LOG_PATH = process.env.HARNESS_AUDIT_LOG ?? '.harness/audit.log';

export async function audit(entry: AuditEntry): Promise<void> {
  if (!POLICY.auditLog) return;
  await appendFile(LOG_PATH, JSON.stringify(entry) + '\\n', 'utf-8').catch(() => {
    /* never let auditing crash a tool call */
  });
}
`;
}

// --- auth (remote only) ----------------------------------------------------

function authTs(): string {
  return `${HEADER}
// Remote (Streamable HTTP) auth. Bearer token by default; swap for OAuth/mTLS
// as your deployment requires. Local stdio mode does not import this file.

export interface AuthResult {
  ok: boolean;
  subject?: string;
  reason?: string;
}

export function authenticate(headers: Record<string, string | undefined>): AuthResult {
  const expected = process.env.HARNESS_MCP_TOKEN;
  if (!expected) {
    return { ok: false, reason: 'HARNESS_MCP_TOKEN not set — refusing unauthenticated remote MCP' };
  }
  const auth = headers['authorization'] ?? headers['Authorization'];
  if (!auth || !auth.startsWith('Bearer ')) {
    return { ok: false, reason: 'missing bearer token' };
  }
  const token = auth.slice('Bearer '.length);
  // Constant-time-ish compare; for production use a real timing-safe compare.
  if (token.length !== expected.length || token !== expected) {
    return { ok: false, reason: 'invalid token' };
  }
  return { ok: true, subject: 'bearer' };
}
`;
}

// --- registries ------------------------------------------------------------

function toolsTs(cfg: HarnessConfig): string {
  return `${HEADER}
import type { ToolCtx } from './policy.js';

export interface ToolDef {
  name: string;
  description: string;
  /** JSON Schema for inputs — hosts inspect this to build their UI. */
  inputSchema: Record<string, unknown>;
  ctx: ToolCtx;
  run: (args: Record<string, unknown>) => Promise<unknown>;
}

/**
 * Deterministic tool registry for ${cfg.name}. Start safe: the example tool
 * needs no privileged capability. Privileged tools declare what they need in
 * \`ctx\` and are gated by the policy.
 */
export const TOOLS: ToolDef[] = [
  {
    name: 'ping',
    description: 'Health probe — returns the harness name and a timestamp. No privileged capability.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
    ctx: { needs: {} },
    run: async () => ({ harness: '${cfg.name}', ok: true, ts: new Date().toISOString() }),
  },
  // Example of a privileged, dangerous tool — denied unless the policy grants
  // shell AND the user approves. Left here as a documented pattern, disabled.
  // {
  //   name: 'run-shell',
  //   description: 'Run a shell command (DANGEROUS).',
  //   inputSchema: { type: 'object', properties: { cmd: { type: 'string' } }, required: ['cmd'] },
  //   ctx: { needs: { shell: true }, dangerous: true },
  //   run: async (args) => { throw new Error('enable shell in policy + wire an executor'); },
  // },
];
`;
}

function resourcesTs(cfg: HarnessConfig): string {
  return `${HEADER}
export interface ResourceDef {
  uri: string;
  name: string;
  mimeType: string;
  read: () => Promise<string>;
}

/** Read-only resources ${cfg.name} exposes to hosts (docs, manifests, memory views). */
export const RESOURCES: ResourceDef[] = [
  {
    uri: 'harness://manifest',
    name: 'Harness manifest',
    mimeType: 'application/json',
    read: async () => (await import('node:fs/promises')).readFile('.harness/manifest.json', 'utf-8'),
  },
  {
    uri: 'harness://capabilities',
    name: 'MCP capability manifest',
    mimeType: 'application/json',
    read: async () => (await import('node:fs/promises')).readFile('.harness/mcp-capabilities.json', 'utf-8'),
  },
];
`;
}

function promptsTs(cfg: HarnessConfig): string {
  return `${HEADER}
export interface PromptDef {
  name: string;
  description: string;
  template: string;
}

/** Branded prompts ${cfg.name} exposes as MCP prompts. */
export const PROMPTS: PromptDef[] = [
  {
    name: 'kickoff',
    description: 'Open a ${cfg.name} session with the harness conventions in context.',
    template: 'You are operating ${cfg.name}. ${cfg.description}\\nUse the harness MCP tools; defer destructive actions to the user.',
  },
];
`;
}

// --- server ----------------------------------------------------------------

function serverTs(cfg: HarnessConfig, remote: boolean): string {
  const transport = remote
    ? `  // Streamable HTTP transport for hosted / team / enterprise deployments.
  // Every request is authenticated before any tool is dispatched.
  const { authenticate } = await import('./auth.js');
  void authenticate; // wire into your HTTP framework's request handler`
    : `  // stdio transport — the default for Claude Code / desktop agent workflows.`;
  return `${HEADER}
import { TOOLS } from './tools.js';
import { RESOURCES } from './resources.js';
import { PROMPTS } from './prompts.js';
import { decide, withTimeout, POLICY } from './policy.js';
import { audit } from './audit.js';

/**
 * MCP server for ${cfg.name} (${remote ? 'remote / Streamable HTTP' : 'local / stdio'}).
 * JSON-RPC 2.0. This is the gated dispatch path: tool -> policy -> (approval) ->
 * timeout-bounded run -> audit. Wire it to your transport of choice.
 */
export async function start(): Promise<void> {
${transport}
  let callsThisTurn = 0;

  process.on('SIGINT', () => process.exit(0));
  console.error('[${cfg.name}] MCP server ready —', TOOLS.length, 'tools,', RESOURCES.length, 'resources,', PROMPTS.length, 'prompts');
  // (Dispatch loop omitted from the scaffold — call dispatch() from your transport.)
  void start;
  // expose for the transport:
  void callsThisTurn;
}

export async function dispatch(toolName: string, args: Record<string, unknown>): Promise<unknown> {
  const tool = TOOLS.find((t) => t.name === toolName);
  if (!tool) {
    await audit({ ts: new Date().toISOString(), tool: toolName, decision: 'error', reason: 'unknown tool' });
    throw new Error('unknown tool: ' + toolName);
  }
  const d = decide(tool.ctx);
  if (!d.allowed) {
    await audit({ ts: new Date().toISOString(), tool: toolName, decision: 'denied', reason: d.reason });
    throw new Error('policy denied ' + toolName + ': ' + d.reason);
  }
  if (d.requiresApproval) {
    await audit({ ts: new Date().toISOString(), tool: toolName, decision: 'approval-required', reason: 'dangerous tool' });
    throw new Error('tool ' + toolName + ' requires user approval (policy.requireApprovalForDangerous)');
  }
  const startedAt = Date.now();
  const out = await withTimeout(() => tool.run(args));
  await audit({ ts: new Date().toISOString(), tool: toolName, decision: 'allowed', reason: 'ok', durationMs: Date.now() - startedAt });
  return out;
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  start().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}

void POLICY;
`;
}

// --- data artifacts --------------------------------------------------------

function policyJson(p: McpPolicy): string {
  return JSON.stringify(p, null, 2) + '\n';
}

function capabilitiesJson(cfg: HarnessConfig): string {
  const remote = cfg.primitives.mcp === 'remote';
  return (
    JSON.stringify(
      {
        schema: 'mcp-capabilities/v1',
        harness: cfg.name,
        mode: cfg.primitives.mcp,
        transport: remote ? 'streamable-http' : 'stdio',
        auth: remote ? 'bearer' : 'none',
        tools: ['ping'],
        resources: ['harness://manifest', 'harness://capabilities'],
        prompts: ['kickoff'],
        policy: cfg.mcpPolicy,
      },
      null,
      2,
    ) + '\n'
  );
}
