// SPDX-License-Identifier: MIT
//
// @metaharness/agntcy — oasf/publish.ts (ADR-240 §2.2)
//
// Real client against the AGNTCY Directory, using the real, published
// `agntcy-dir` npm package (https://www.npmjs.com/package/agntcy-dir,
// TypeScript SDK, gRPC via ConnectRPC). An earlier version of this file
// claimed no such package existed — that was wrong; the original check only
// guessed scoped names like `@agntcy/dir` and got 404s. The real package is
// unscoped (`agntcy-dir`). Verified live against a local Directory server
// (Go apiserver + zot OCI registry + postgres, built and run from
// github.com/agntcy/dir's own `install/docker/docker-compose.yml`) — a real
// record was pushed and published against it during development of this file.
//
// TAXONOMY MAPPING (previously the one deliberately-unmapped gap, now real):
// `src/oasf/taxonomy.generated.json` ships all 364 genuine leaf skills from a
// real checkout of github.com/agntcy/oasf's `schema/skills/**`, generated by
// `scripts/generate-oasf-taxonomy.mjs` (re-run that script against a fresh
// checkout to pick up upstream taxonomy changes). `KNOWN_AGENT_SKILLS` below
// maps this repo's REAL internal capability vocabulary — the exact ids
// `harness-genome`'s `plan.agents`/`plan.skills`/`genome.agent_topology`
// actually emit (see `project.ts`'s `projectToOasf`) — onto that generated
// data; every id below is asserted to exist in the generated table by this
// file's own test suite, so a stale/renamed upstream id fails a test rather
// than silently mis-tagging every published record.
//
// Composite id derivation (`category*10000 + subcategory*100 + leaf`):
// reverse-engineered from agntcy/dir-sdk-javascript's own example.js (two
// worked examples) and confirmed structurally against every category/
// subcategory/leaf JSON's own `uid` field. One real ambiguity this
// implementation resolves correctly: a file that shares its own subcategory
// directory's name (e.g. `code_generation/code_generation.json`) is the
// SUBCATEGORY's own definition (`extends` points at the CATEGORY) — not a
// leaf under itself — and must be excluded from the leaf table, or every
// composite id built from it would silently collide with the taxonomy's real
// leaf uid=1 under that subcategory. `generate-oasf-taxonomy.mjs` excludes it;
// an earlier draft of this file's own comments described a wrong "self-node,
// leaf defaults to 1" theory before this was traced through the real
// `agntcy/oasf` tree.
//
// IMPORTANT (found empirically against a live server, see this file's test
// suite): send `{ id }` ONLY — no `name` field. The server resolves the
// class name from the numeric id internally; supplying ANY `name` value
// (even the taxonomy's own dotted path, e.g.
// "software_engineering/code_generation/code_generation") makes it run a
// separate, stricter lookup that currently rejects every value tried,
// including the taxonomy's own real names — this looks like a real,
// reportable bug/version-skew in the live server's validator, not a mapping
// error on this repo's side. Filed upstream: see README.md "Upstream
// reports" (agntcy/dir#1943).

import { Client, Config } from 'agntcy-dir';
import { create } from '@bufbuild/protobuf';
import { RecordRefsSchema, PublishRequestSchema } from '@buf/agntcy_dir.bufbuild_es/agntcy/dir/routing/v1/routing_service_pb.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import type { OasfRecord } from './record.js';

// Read as a runtime asset rather than a static JSON import — avoids
// requiring `resolveJsonModule` + JSON import-attribute support (Node
// >=20.10 only) across the whole package just for this one generated file,
// and keeps `taxonomy.generated.json` a plain build asset the "build" script
// copies alongside the compiled .js (see package.json), rather than
// something tsc needs to understand.
const taxonomyPath = fileURLToPath(new URL('./taxonomy.generated.json', import.meta.url));
const taxonomy: unknown = JSON.parse(readFileSync(taxonomyPath, 'utf8'));

export interface PublishResult {
  published: boolean;
  reason?: string;
  /** The Directory's content-addressed reference for the pushed record, when published. */
  ref?: unknown;
}

export interface PublishTarget {
  /** Harness name — not tracked by OasfRecord itself; the caller (whoever
   * knows the harness's package name) supplies it rather than this function
   * inventing one. */
  name: string;
  version: string;
  /** Defaults to AGNTCY_DIRECTORY_ENDPOINT, then DIRECTORY_CLIENT_SERVER_ADDRESS
   * (the agntcy-dir SDK's own env var), then undefined (fails closed). */
  serverAddress?: string;
  /**
   * A pre-configured SDK `Config` — set `config.authMode` to `'tls'`, `'x509'`,
   * or `'jwt'` (plus the matching `tls*`/`jwtAudience`/`spiffeEndpointSocket`
   * fields) to authenticate for real against a production Directory instead
   * of the SDK's insecure plaintext default. When omitted, this function
   * builds one via `Config.loadFromEnv()`, so any `DIRECTORY_CLIENT_AUTH_MODE`
   * / `DIRECTORY_CLIENT_TLS_*` / `DIRECTORY_CLIENT_JWT_AUDIENCE` environment
   * variables already set (the SDK's own documented convention — see its
   * README's "Configuration" section) take effect automatically. `authMode:
   * 'oidc'` is not supported through this path: it requires an interactive
   * PKCE login this synchronous publish call has no way to drive — pass a
   * `Config` with a pre-cached `authToken` instead if OIDC is your auth mode.
   */
  config?: Config;
}

interface TaxonomyLeaf {
  id: number;
  path: string;
  caption: string;
  description: string;
}

export const TAXONOMY: TaxonomyLeaf[] = taxonomy as TaxonomyLeaf[];
const TAXONOMY_IDS = new Set(TAXONOMY.map((leaf) => leaf.id));

/** Assert-and-look-up: throws at import time (loud, not a silent typo) if a
 * path below no longer exists in the generated taxonomy — e.g. after
 * re-running generate-oasf-taxonomy.mjs against a renamed/removed upstream
 * leaf. Prefer this over hand-copying numeric ids. */
function leafId(path: string): number {
  const leaf = TAXONOMY.find((l) => l.path === path);
  if (!leaf) {
    throw new Error(
      `oasf/publish.ts: taxonomy leaf "${path}" not found in taxonomy.generated.json — ` +
        `re-run scripts/generate-oasf-taxonomy.mjs against a current agntcy/oasf checkout, ` +
        `then fix or remove this mapping if the leaf was renamed/removed upstream.`,
    );
  }
  return leaf.id;
}

// This repo's REAL internal capability vocabulary — not a guess. These are
// exactly the ids `harness-genome`'s `buildGenomeReport()` emits into
// `plan.agents` (23 possible values, archetype-dependent), `plan.skills` (4
// possible values), and `genome.agent_topology` (a fixed 4-value set:
// maintainer/tester/security/release) — see `packages/create-agent-harness/
// src/analyze-repo.ts`'s `ARCHETYPES` and `genome-scorers.ts`'s
// `resolveAgentTopology()`. `project.ts#projectToOasf` feeds all three pools
// into `OasfRecord.capabilities[].id` verbatim (no import from this package
// to that one — the kernel-boundary discipline in project.ts's own header —
// so this table must be kept in sync by hand against that real vocabulary,
// not derived automatically). Three internal names have no confidently
// fitting real leaf and are intentionally left unmapped — `worker`, `scout`,
// `escalator` — for these, `projectAnnotations` simply has no
// `skill.taxonomyId.*` entry to record (still lists the capability itself
// under `capability.*`, per this file's "never silently drop" rule).
export const KNOWN_AGENT_SKILLS: Record<string, { id: number }> = {
  // agent_topology (4/4 mapped)
  maintainer: { id: leafId('software_engineering/code_quality/code_migration') },
  tester: { id: leafId('software_engineering/software_testing/unit_integration_testing') },
  security: { id: leafId('cybersecurity/application_security/secure_coding') },
  release: { id: leafId('devops_cloud_infra/deployment_release/release_management') },
  // agents (20/23 mapped — worker, scout, escalator deliberately absent)
  orchestrator: { id: leafId('ai_ml_engineering/agent_orchestration/agentic_workflow_orchestration') },
  planner: { id: leafId('ai_ml_engineering/agent_orchestration/multi_agent_planning') },
  critic: { id: leafId('ai_ml_engineering/model_evaluation/llm_judge_evaluation') },
  reviewer: { id: leafId('software_engineering/code_quality/code_review') },
  'test-writer': { id: leafId('software_engineering/software_testing/test_case_generation') },
  architect: { id: leafId('software_engineering/software_architecture/system_design') },
  implementer: { id: leafId('software_engineering/api_development/api_implementation') },
  'data-curator': { id: leafId('ai_ml_engineering/training_data_engineering/data_curation') },
  trainer: { id: leafId('ai_ml_engineering/model_training/deep_learning_training') },
  evaluator: { id: leafId('ai_ml_engineering/model_evaluation/quality_evaluation') },
  deployer: { id: leafId('devops_cloud_infra/deployment_release/deployment_orchestration') },
  synthesizer: { id: leafId('research_knowledge_productivity/web_search/information_synthesis') },
  'fact-checker': { id: leafId('research_knowledge_productivity/web_search/fact_verification') },
  citer: { id: leafId('research_knowledge_productivity/research/citation_management') },
  responder: { id: leafId('devops_cloud_infra/site_reliability_engineering/incident_response') },
  'runbook-runner': { id: leafId('devops_cloud_infra/site_reliability_engineering/incident_response') },
  postmortem: { id: leafId('devops_cloud_infra/site_reliability_engineering/postmortem_authoring') },
  analyst: { id: leafId('data_engineering_analytics/data_analytics/exploratory_data_analysis') },
  strategist: { id: leafId('business_professional/business_strategy/strategic_advisory') },
  'ops-coordinator': { id: leafId('devops_cloud_infra/deployment_release/deployment_orchestration') },
  // skills (4/4 mapped)
  'run-swarm': { id: leafId('ai_ml_engineering/agent_orchestration/multi_agent_coordination') },
  'memory-inspect': { id: leafId('ai_ml_engineering/agent_development/agent_memory') },
  'plan-change': { id: leafId('ai_ml_engineering/agent_orchestration/multi_agent_planning') },
  'eval-report': { id: leafId('ai_ml_engineering/model_evaluation/benchmark_execution') },
};
// EMPIRICALLY CONFIRMED against the real live Directory server, reproducibly
// (verified across a container restart, ruling out local caching): the
// remote schema.oasf.outshift.com validator the server delegates to
// currently recognizes id=60101 and rejects EVERY OTHER numerically-correct
// composite id tried from the CURRENT public agntcy/oasf schema tree —
// including ids for well-known subcategories (software_testing=60501,
// application_security=100101) that an earlier version of this file believed
// confirmed. This is a deeper instance of the same upstream inconsistency
// already reported in agntcy/dir#1943 (originally filed for the `name`
// field failing on every value tried) — this shows the numeric `id`-only
// path is ALSO broken beyond a small, seemingly-arbitrary subset. Filed as
// an update to that issue with a minimal repro.
//
// Consequence for this function: sending KNOWN_AGENT_SKILLS' real ids
// directly on the wire would make live pushes FAIL for every record whose
// capabilities don't happen to map to the one confirmed-good id — a real
// regression versus the old 5-entry table, which accidentally always fell
// back to 60101 for almost everything. So `projectSkills` sends ONLY
// `CONFIRMED_LIVE_SKILL` in the actual wire payload (matches today's proven
// behavior exactly) while `projectAnnotations` still records each
// capability's REAL, correctly-derived taxonomy id — nothing is silently
// dropped, and flipping `SEND_REAL_TAXONOMY_IDS` to `true` is the entire
// fix once upstream's validator accepts the full schema tree (tracked by
// the linked issue).
const SEND_REAL_TAXONOMY_IDS = false;
const CONFIRMED_LIVE_SKILL = { id: leafId('software_engineering/code_generation/text_to_code') }; // = 60101, the one id currently accepted live

function projectSkills(record: OasfRecord): Array<{ id: number }> {
  // The real Directory server requires a non-empty skills array (validated
  // live — see this file's test suite).
  if (!SEND_REAL_TAXONOMY_IDS) return [CONFIRMED_LIVE_SKILL];
  if (record.capabilities.length === 0) return [CONFIRMED_LIVE_SKILL];
  const seen = new Set<number>();
  const skills: Array<{ id: number }> = [];
  for (const cap of record.capabilities) {
    const mapped = KNOWN_AGENT_SKILLS[cap.id] ?? CONFIRMED_LIVE_SKILL;
    if (!seen.has(mapped.id)) {
      seen.add(mapped.id);
      skills.push(mapped);
    }
  }
  return skills;
}

function projectAnnotations(record: OasfRecord): Record<string, string> {
  const annotations: Record<string, string> = {};
  for (const cap of record.capabilities) {
    annotations[`capability.${cap.kind}.${cap.id}`] = 'true';
    // Real, correctly-derived taxonomy id for this capability, recorded even
    // though (per the note above) it may not be what actually went into
    // `skills[]` above — never silently dropped.
    const realTaxonomyId = KNOWN_AGENT_SKILLS[cap.id]?.id;
    if (realTaxonomyId !== undefined) annotations[`skill.taxonomyId.${cap.id}`] = String(realTaxonomyId);
  }
  for (const proto of record.supportedProtocols) annotations[`host.${proto.host}`] = 'true';
  annotations['model.recommendedMode'] = record.modelRequirements.recommendedMode;
  annotations['model.estCostPerRunUsd'] = String(record.modelRequirements.estCostPerRunUsd);
  annotations['resource.mcpEnabled'] = String(record.resourceEnvelope.mcpEnabled);
  annotations['resource.shellAccess'] = String(record.resourceEnvelope.shellAccess);
  annotations['resource.networkAccess'] = String(record.resourceEnvelope.networkAccess);
  annotations['resource.fileWriteAccess'] = String(record.resourceEnvelope.fileWriteAccess);
  for (const scope of record.securityScopes) annotations[`security.${scope.severity}.${scope.id}`] = scope.title;
  for (const ev of record.evaluationHistory) annotations[`evaluation.${ev.source}.${ev.metric}`] = String(ev.value);
  // pricingMeteringClass intentionally never appears here — projectToOasf (project.ts)
  // never populates it (fails closed, see record.ts's file header), so there is
  // nothing to project.
  return annotations;
}

/** Rebuild a Config with a different serverAddress by re-running the real
 * constructor (see the call site's comment for why a plain property
 * assignment is wrong here) — every other field carries over unchanged. */
function withServerAddress(config: Config, serverAddress: string): Config {
  return new Config(
    serverAddress,
    config.dirctlPath,
    config.spiffeEndpointSocket,
    config.authMode,
    config.jwtAudience,
    config.tlsCaFile,
    config.tlsCertFile,
    config.tlsKeyFile,
    config.authToken,
    config.tlsServerName,
    config.tlsSkipVerify,
    config.oidcIssuer,
    config.oidcClientId,
    config.oidcClientSecret,
    config.oidcRedirectUri,
    config.oidcCallbackPort,
    config.oidcAuthTimeout,
    config.oidcScopes,
    config.oidcAccessToken,
    config.dockerConfig,
  );
}

/**
 * Push an OasfRecord to a real AGNTCY Directory server and publish it to the
 * routing table (making it discoverable). Fails closed with a clear reason
 * when no server is configured or the call fails — never a silent no-op,
 * never a faked success.
 */
export async function publishToDirectory(record: OasfRecord, target: PublishTarget): Promise<PublishResult> {
  if (record.schema !== 1) {
    return { published: false, reason: 'invalid OasfRecord: unsupported schema version' };
  }

  // Fail-closed server resolution stays independent of the SDK's own
  // Config.loadFromEnv() default (127.0.0.1:8888) — loadFromEnv() ALWAYS
  // returns a non-empty serverAddress, which would silently attempt a real
  // network call to localhost even when the caller configured nothing.
  const serverAddress = target.serverAddress ?? process.env.AGNTCY_DIRECTORY_ENDPOINT ?? process.env.DIRECTORY_CLIENT_SERVER_ADDRESS;
  if (!serverAddress) {
    return {
      published: false,
      reason: 'No Directory server configured — set AGNTCY_DIRECTORY_ENDPOINT (or the SDK\'s own DIRECTORY_CLIENT_SERVER_ADDRESS) to a real server address.',
    };
  }

  // SECURITY: real TLS/x509/JWT auth, not the insecure default. `target.config`
  // (explicit) wins; otherwise Config.loadFromEnv() picks up the SDK's own
  // DIRECTORY_CLIENT_AUTH_MODE/TLS_*/JWT_AUDIENCE/SPIFFE_SOCKET_PATH env vars,
  // so a deployment that exports those gets real authentication automatically
  // — this function no longer forces `authMode: ''` (plaintext, no auth) the
  // way an earlier version did. Config.createGRPCTransport() (below) already
  // implements the real tls/x509/jwt transport construction for every mode
  // this accepts; this file only needed to stop discarding the caller's
  // configuration, not reimplement transport security itself.
  //
  // withServerAddress() re-runs the Config CONSTRUCTOR rather than assigning
  // `.serverAddress` on an already-built instance — the constructor is where
  // the SDK normalizes a bare `host:port` into a full URL (`http://` for
  // plaintext, `https://` for tls/x509/jwt/oidc); a plain property assignment
  // skips that entirely and the transport layer then throws `Invalid URL` on
  // the un-prefixed address (caught by this file's own live-server test).
  const loaded = target.config ?? Config.loadFromEnv();
  const config = withServerAddress(loaded, serverAddress);
  if (config.authMode === 'oidc') {
    return {
      published: false,
      reason: 'authMode "oidc" requires an interactive PKCE login this non-interactive publish call cannot drive — pass a Config with a pre-cached authToken instead.',
    };
  }

  const dirRecord = {
    data: {
      name: target.name,
      version: target.version,
      schema_version: '0.8.0',
      description: 'MetaHarness-generated harness (ADR-240 §2.2 projection)',
      authors: ['metaharness'],
      created_at: record.generatedAt,
      skills: projectSkills(record),
      // Real locator `type` enum is unspecified|helm_chart|container_image|
      // package|source_code|binary|url (github.com/agntcy/oasf schema/objects/
      // locator.json) — describes artifact download locations, not runtime
      // hosts. This repo's deploymentOptions.hosts (e.g. "claude-code") isn't
      // an artifact locator in that sense, so it stays out of locators (which
      // the live server validates whenever present) and goes into
      // annotations instead, alongside every other capability we track.
      locators: [] as unknown[],
      domains: [] as unknown[],
      annotations: projectAnnotations(record),
      modules: [] as unknown[],
    },
  };

  try {
    const transport = await Client.createGRPCTransport(config);
    const client = new Client(config, transport);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pushedRefs = await client.push([dirRecord as any]);
    if (pushedRefs.length === 0) {
      return { published: false, reason: 'Directory push returned no record reference' };
    }
    await client.publish(
      create(PublishRequestSchema, { request: { case: 'recordRefs', value: create(RecordRefsSchema, { refs: pushedRefs }) } }),
    );
    return { published: true, ref: pushedRefs[0] };
  } catch (err) {
    return { published: false, reason: `Directory push/publish failed: ${err instanceof Error ? err.message : String(err)}` };
  }
}

/** Exported for this file's own tests — asserts every KNOWN_AGENT_SKILLS
 * entry's id genuinely exists in the generated taxonomy (leafId() already
 * throws at import time on a miss; this re-check exists so a test failure
 * names the exact file, not a module-load crash). */
export function __allMappedIdsExistInTaxonomy(): boolean {
  return Object.values(KNOWN_AGENT_SKILLS).every((v) => TAXONOMY_IDS.has(v.id)) && TAXONOMY_IDS.has(CONFIRMED_LIVE_SKILL.id);
}
