#!/usr/bin/env node
// SPDX-License-Identifier: MIT
//
// examples/quickstart/quickstart.mjs
//
// "From zero to validated harness in one script." A runnable
// end-to-end demo that exercises the full meta-harness flow without
// shelling out to npm or pulling network resources:
//
//   1. scaffold a `demo-bot` harness from the `minimal` template
//   2. run the `harness validate` umbrella against the output
//   3. print a summary
//
// Use this to:
//   - Verify a local build works end-to-end
//   - Onboard a new contributor (single command run)
//   - Smoke-test a pre-release tag locally
//
// Run with:
//   node examples/quickstart/quickstart.mjs               # default: claude-code
//   node examples/quickstart/quickstart.mjs --host=codex  # any of 6 hosts
//   node examples/quickstart/quickstart.mjs --keep        # don't auto-clean

import { mkdtemp, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
// Import the BUILT modules — pure runtime, no TS toolchain needed.
// (For vitest-based tests, the equivalent flow lives in
//  __tests__/e2e-scaffold-validate.test.ts and imports from src/.)
import { scaffold } from '../../packages/create-agent-harness/dist/index.js';
import { validate } from '../../packages/create-agent-harness/dist/validate.js';

const args = process.argv.slice(2);
const HOST = args.find(a => a.startsWith('--host='))?.slice('--host='.length) ?? 'claude-code';
const TEMPLATE = args.find(a => a.startsWith('--template='))?.slice('--template='.length) ?? 'minimal';
const KEEP = args.includes('--keep');
const NAME = args.find(a => a.startsWith('--name='))?.slice('--name='.length) ?? 'demo-bot';

const VALID_HOSTS = ['claude-code', 'codex', 'pi-dev', 'hermes', 'openclaw', 'rvm'];
if (!VALID_HOSTS.includes(HOST)) {
  console.error(`[quickstart] invalid --host=${HOST} (choose: ${VALID_HOSTS.join(', ')})`);
  process.exit(2);
}

function step(n, msg) { process.stderr.write(`\n[step ${n}] ${msg}\n`); }
function log(msg) { process.stderr.write(`  ${msg}\n`); }

async function main() {
  const t0 = Date.now();

  step(1, `Scaffold a "${NAME}" harness from template="${TEMPLATE}" host="${HOST}"`);
  const dir = await mkdtemp(join(tmpdir(), `ahg-quickstart-`));
  log(`output dir: ${dir}`);
  const r = await scaffold({
    name: NAME,
    template: TEMPLATE,
    host: HOST,
    description: 'Generated by quickstart.mjs',
    targetDir: dir,
    force: true,
    generatorVersion: '0.1.0',
  });
  log(`wrote ${r.paths.length} files, manifest at ${r.manifestPath.slice(dir.length + 1)}`);
  if (r.unresolved.length) {
    log(`WARNING: ${r.unresolved.length} unresolved template vars: ${r.unresolved.join(', ')}`);
  }

  step(2, 'Validate the scaffolded output');
  const v = await validate([dir, '--skip-gcp']);
  for (const line of v.lines) log(line);
  if (v.code !== 0) {
    process.stderr.write(`\n[quickstart] FAIL: validate exit code ${v.code}\n`);
    process.exit(v.code);
  }

  step(3, 'Summary');
  const fileCount = (await listAllFiles(dir)).length;
  const ms = Date.now() - t0;
  log(`generated ${fileCount} files in ${ms}ms`);
  log(`scaffold paths reported: ${r.paths.length}`);
  log(`validation: HEALTHY`);

  if (KEEP) {
    log(`KEPT at ${dir} (--keep)`);
  } else {
    await rm(dir, { recursive: true, force: true });
    log(`cleaned up ${dir}`);
  }

  process.stderr.write(`\n[quickstart] DONE in ${ms}ms — host=${HOST} template=${TEMPLATE}\n`);
}

async function listAllFiles(dir) {
  const out = [];
  async function walk(d) {
    const entries = await readdir(d, { withFileTypes: true });
    for (const ent of entries) {
      const p = join(d, ent.name);
      if (ent.isDirectory()) await walk(p);
      else out.push(p);
    }
  }
  await walk(dir);
  return out;
}

main().catch(err => {
  process.stderr.write(`\n[quickstart] FAIL: ${err?.stack ?? err}\n`);
  process.exit(1);
});
